# Generated by Django 4.1.3 on 2023-03-17 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_alter_item_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='contactnumber',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
