# Generated by Django 4.1.3 on 2023-03-17 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_item_contactnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='contactnumber',
            field=models.CharField(default='01632398271', max_length=15),
        ),
    ]
