# Generated by Django 4.1.3 on 2023-03-17 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_alter_item_contactnumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='contactnumber',
            new_name='contact_number',
        ),
    ]
