# Generated by Django 4.1.3 on 2023-03-17 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0006_rename_contactnumber_item_contact_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category_images'),
        ),
    ]
