# Generated by Django 4.1.3 on 2023-03-17 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aitverfullprojectteammember',
            name='image',
            field=models.ImageField(null=True, upload_to='members_images'),
        ),
    ]
